### ISSUE TITLE
webtrees 2.0.23 / error when searching for a shared place name

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#121]
```
Call to a member function getPreference() on null …/modules_v4/vesta_shared_places/resources/views/search-results-ext_20.phtml:138
#0 …/app/View.php(184): include()
#1 …/app/View.php(281): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make()
#3 …/modules_v4/vesta_shared_places/resources/views/search-general-page-ext_20.phtml(123): view()
#4 …/app/View.php(184): include('/mnt/web109/a3/...')
#5 …/app/View.php(281): Fisharebest\Webtrees\View->render()
#6 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make()
#7 …/app/Http/ViewResponseTrait.php(51): view()
#8 …/modules_v4/vesta_shared_places/patchedWebtrees/Http/RequestHandlers/SearchGeneralPageExt_20.php(191): Cissee\WebtreesExt\Http\RequestHandlers\SearchGeneralPageExt_20->viewResponse()
#9 …/app/Http/Middleware/WrapHandler.php(83): Cissee\WebtreesExt\Http\RequestHandlers\SearchGeneralPageExt_20->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
```

**Comment by ric2016** [comment]
Duplicate of #117? Does this still occur in the latest Vesta release?

**Comment by hartenthaler** [comment]
Sorry! The latest version was not uploaded to my 2.0.23 server. The error disappeared with the latest version.
