### ISSUE TITLE
Editing of shared locations (_LOC) not possible

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#140]
When I try to edit a shared location record there is an error message
```
Fisharebest\Webtrees\Http\RequestHandlers\CreateLocationModal …/vendor/aura/router/src/Map.php:189
#0 …/app/Factories/RouteFactory.php(62): Aura\Router\Map->getRoute()
vesta-webtrees-2-custom-modules/vesta_classic_laf#1 …/app/Helpers/functions.php(132): Fisharebest\Webtrees\Factories\RouteFactory->route()
vesta-webtrees-2-custom-modules/vesta_classic_laf#2 …/app/Elements/XrefLocation.php(60): route()
vesta-webtrees-2-custom-modules/vesta_classic_laf#3 …/modules_v4/vesta_classic_look_and_feel/resources/views/edit/edit-gedcom-fields-ext2.phtml(86): Fisharebest\Webtrees\Elements\XrefLocation->edit()
vesta-webtrees-2-custom-modules/vesta_classic_laf#4 …/app/View.php(183): include('...')
vesta-webtrees-2-custom-modules/vesta_classic_laf#5 …/app/View.php(278): Fisharebest\Webtrees\View->render()
vesta-webtrees-2-custom-modules/vesta_classic_laf#6 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
vesta-webtrees-2-custom-modules/vesta_classic_laf#7 …/modules_v4/vesta_classic_look_and_feel/resources/views/edit/edit-gedcom-fields-switch.phtml(33): view()
```

**Comment by ric2016** [comment]
Original issue (edit dialog error) is fixed in code.
I have created a separate [issue](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/issues/141) for the links provlem, but I don't expect to be able to fix it easily/soon.
