### ISSUE TITLE
Fatal error - V2.1.16.1.6

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_shared_places#158]
Fatal error in module: vesta_shared_places
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 3001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://raw.githubusercontent.com/vesta-webtrees-2-custom-modules/vesta_shared_places/master/metadata.json in /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish() #3 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke() #4 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #5 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}() #6 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke() #7 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #8 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke() #9 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #10 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke() #11 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer() #12 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync() #13 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request() #14 /var/www/vhosts/xxx.de/httpdocs/webtrees/modules_v4/vesta_common/patchedWebtrees/Module/ModuleMetaTrait.php(86): GuzzleHttp\Client->get() #15 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Cache.php(60): Cissee\Webtrees\Module\SharedPlaces\PlaceholderModule->Cissee\WebtreesExt\Module\{closure}() #16 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/symfony/cache/LockRegistry.php(113): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}() #17 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/symfony/cache/Traits/ContractsTrait.php(100): Symfony\Component\Cache\LockRegistry::compute() #18 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/symfony/cache-contracts/CacheTrait.php(72): Symfony\Component\Cache\Adapter\AbstractAdapter->Symfony\Component\Cache\Traits\{closure}() #19 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/symfony/cache/Traits/ContractsTrait.php(107): Symfony\Component\Cache\Adapter\AbstractAdapter->contractsGet() #20 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/symfony/cache-contracts/CacheTrait.php(35): Symfony\Component\Cache\Adapter\AbstractAdapter->doGet() #21 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Cache.php(61): Symfony\Component\Cache\Adapter\AbstractAdapter->get() #22 /var/www/vhosts/xxx.de/httpdocs/webtrees/modules_v4/vesta_common/patchedWebtrees/Module/ModuleMetaTrait.php(97): Fisharebest\Webtrees\Cache->remember() #23 /var/www/vhosts/xxx.de/httpdocs/webtrees/modules_v4/vesta_common/patchedWebtrees/Module/ModuleMetaTrait.php(121): Cissee\Webtrees\Module\SharedPlaces\PlaceholderModule->customModuleLatestMetaDatas() #24 /var/www/vhosts/xxx.de/httpdocs/webtrees/modules_v4/vesta_common/patchedWebtrees/Module/ModuleMetaTrait.php(26): Cissee\Webtrees\Module\SharedPlaces\PlaceholderModule->customModuleMetaData() #25 /var/www/vhosts/xxx.de/httpdocs/webtrees/modules_v4/vesta_shared_places/PlaceholderModule.php(71): Cissee\Webtrees\Module\SharedPlaces\PlaceholderModule->minRequiredWebtreesVersion() #26 /var/www/vhosts/xxx.de/httpdocs/webtrees/modules_v4/vesta_shared_places/module.php(52): Cissee\Webtrees\Module\SharedPlaces\PlaceholderModule->ifIncompatible() #27 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Services/ModuleService.php(722): include('...') #28 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Services/ModuleService.php(696): Fisharebest\Webtrees\Services\ModuleService::load() #29 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}() #30 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/illuminate/collections/Collection.php(695): array_map() #31 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Services/ModuleService.php(705): Illuminate\Support\Collection->map() #32 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Services/ModuleService.php(617): Fisharebest\Webtrees\Services\ModuleService->customModules() #33 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Cache.php(60): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() #34 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/symfony/cache/Adapter/ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}() #35 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Cache.php(61): Symfony\Component\Cache\Adapter\ArrayAdapter->get() #36 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Services/ModuleService.php(650): Fisharebest\Webtrees\Cache->remember() #37 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Services/ModuleService.php(573): Fisharebest\Webtrees\Services\ModuleService->all() #38 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/UseLanguage.php(84): Fisharebest\Webtrees\Services\ModuleService->findByInterface() #39 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/UseLanguage.php(63): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages() #40 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #41 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #42 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #43 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #44 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #45 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle() #46 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #47 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle() #48 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #49 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #50 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #51 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #52 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #53 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #54 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #55 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #56 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #57 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #58 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #59 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #60 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #61 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #62 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #63 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #64 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #65 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #66 /var/www/vhosts/xxx.de/httpdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #67 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #68 /var/www/vhosts/xxx.de/httpdocs/webtrees/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #69 /var/www/vhosts/xxx.de/httpdocs/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #70 {main}

**Comment by ric2016** [comment]
I don't think this is reproducible?

**Comment by webtrees-pesz** [comment]
I don't think so. What could be the reason for this exception? CURL?
