### ISSUE TITLE
error when showing an shared location record

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_shared_places#54]
When I try to show a location record, which I added today, I get an error:
`
Return value of Fisharebest\Webtrees\Services\TreeService::find() must be an instance of Fisharebest\Webtrees\Tree, null returned …/app/Services/TreeService.php:136
#0 …/modules_v4/vesta_shared_places/patchedWebtrees/Services/SearchServiceExt.php(138): Fisharebest\Webtrees\Services\TreeService->find(4)
#1 …/modules_v4/vesta_shared_places/patchedWebtrees/Services/SearchServiceExt.php(158): Cissee\WebtreesExt\Services\SearchServiceExt->Cissee\WebtreesExt\Services\{closure}(Object(stdClass))
#2 …/modules_v4/vesta_shared_places/patchedWebtrees/Services/SearchServiceExt.php(93): Cissee\WebtreesExt\Services\SearchServiceExt->paginateQuery(Object(Illuminate\Database\Query\Builder), Object(Closure), Object(Closure), 0, 2147483646)
#3 …/modules_v4/vesta_shared_places/SharedPlacesModule.php(642): Cissee\WebtreesExt\Services\SearchServiceExt->searchLocationsEOL(Array, Array)
#4 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(365): Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule->gov2loc(Object(Vesta\Model\GovReference), Object(Fisharebest\Webtrees\Tree))
#5 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(724): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::gov2plac(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), Object(Vesta\Model\GovReference), Object(Fisharebest\Webtrees\Tree))
#6 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(649): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->getHierarchy(false, 1, true, Object(Fisharebest\Localization\Locale\LocaleDe), '2459248', '2021', Object(Vesta\Model\GovReference), Object(Fisharebest\Webtrees\Tree), 'shared place vi...', true)
#7 …/modules_v4/vesta_personal_facts/FunctionsPrintWithHooks.php(56): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->factPlaceAdditions(Object(Vesta\Model\PlaceStructure))
#8 [internal function]: Cissee\Webtrees\Module\PersonalFacts\FunctionsPrintWithHooks->Cissee\Webtrees\Module\PersonalFacts\{closure}(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), '_vesta_gov4webt...')
#9 …/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array)
#10 …/modules_v4/vesta_personal_facts/FunctionsPrintWithHooks.php(57): Illuminate\Support\Collection->map(Object(Closure))
#11 …/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended.php(295): Cissee\Webtrees\Module\PersonalFacts\FunctionsPrintWithHooks->formatPlaceNameAndSubRecords(Object(Vesta\Model\PlaceStructure))
#12 …/modules_v4/vesta_common/HookInterfaces/FunctionsPlaceUtils.php(46): Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended->plac2html(Object(Vesta\Model\PlaceStructure))
#13 …/modules_v4/vesta_shared_places/patchedWebtrees/Http/RequestHandlers/SharedPlacePage.php(115): Vesta\Hook\HookInterfaces\FunctionsPlaceUtils::plac2html(Object(Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule), Object(Vesta\Model\PlaceStructure))
#14 …/app/Http/Middleware/WrapHandler.php(83): Cissee\WebtreesExt\Http\RequestHandlers\SharedPlacePage->handle(Object(Nyholm\Psr7\ServerRequest))
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#16 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(213): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 …/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(161): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
`

**Comment by hartenthaler** [comment]
... maybe this happened when I was not logged in. Now I'm logged in, deleted the location record one level higher than the new location record, selected the new location record again, get access without an error, and was able to delete it. Now I will add it again. At the moment my problem is solved.

**Comment by ric2016** [comment]
I'm afraid I don't see how it is possible to end up at the point where an attempt is made to access the private tree with id '4' - Unless you edited database rows directly?

Let me know if you can reproduce this.

**Comment by hartenthaler** [comment]
No, I didn't edit database rows directly. I remember that I started after some hours with no activity using the already opened browser. I opened Lists / shared Places. I wondered about the message in the top right corner, that I should activate the shared places module, instead of the normal message "View Shared places hierarchy". Then I tried to access the location record and got the error. Then I tried something else and got the login page. Logging in and everything works again as expected. I'm not sure if this helps to identify the reason for this error. If it happens again, I will be more precise.

**Comment by ric2016** [comment]
> I remember that I started after some hours with no activity using the already opened browser.

Apparently you were somehow 'partially' logged out, maybe due to an expired session. And different parts of webtrees react differently to this ill-defined state? Anyway I guess it won't be easy to reproduce.
